# Generated by Django 3.1.2 on 2021-05-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskProject', '0002_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadro',
            name='descricao',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
