# Generated by Django 3.1.2 on 2021-05-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskProject', '0003_auto_20210508_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadro',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
