# Generated by Django 3.1.2 on 2021-06-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskProject', '0006_auto_20210612_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='data_previsao',
            new_name='data_previsao_termino',
        ),
    ]
