# Generated by Django 3.1.2 on 2021-06-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskProject', '0009_auto_20210618_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='quadro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='taskProject.quadro'),
        ),
    ]
