# Generated by Django 3.1.2 on 2021-06-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskProject', '0010_auto_20210618_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('1', 'Pendente'), ('2', 'Em Andamento'), ('3', 'Concluída')], default='1', max_length=1),
        ),
    ]
