# Generated by Django 3.1.2 on 2021-07-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskProject', '0012_auto_20210710_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
