# Generated by Django 2.2.24 on 2021-07-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskProject', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
